In [1]:
%matplotlib inline

In [2]:
# Import Dependencies
import scipy
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from scipy import stats
import os

In [3]:
cd_country = "data/country_codes.csv"
cd_country_df = pd.read_csv(cd_country)
cd_country_df.columns.tolist()
cd_country_df.columns = ['Code','Description',  'CodeType' , 'Deprecated',  'Created',  'Modified',  ' ']
cd_country_df.columns.tolist()

['Code', 'Description', 'CodeType', 'Deprecated', 'Created', 'Modified', ' ']

In [4]:
f_cd_country_df = cd_country_df[['Code','Description']]
f_cd_country_df

   Code                                        Description
0   ALL   All countries used when reporting survey indices
1    BE                                            Belgium
2    BG                                           Bulgaria
3    CA                                             Canada
4    DE                                            Germany
5    DK                                            Denmark
6    EE                                            Estonia
7    ES                                              Spain
8    FI                                            Finland
9    FO                                      Faroe Islands
10   FR                                             France
11   GG                       UK (Channel Island Guernsey)
12   GL                                          Greenland
13   IE                                            Ireland
14   IM                                   UK (Isle of Man)
15   IS                                            Iceland
16   IT                                              Italy
17   JE                         UK (Channel Island Jersey)
18   LT                                          Lithuania
19   LV                                             Latvia
20   NL                                        Netherlands
21   NO                                             Norway
22  OT1                              First unknown country
23  OT2                             Second unknown country
24  OT3                              Third unknown country
25   PL                                             Poland
26   PT                                           Portugal
27   RU                                             Russia
28   SE                                             Sweden
29   UK                                     United Kingdom
30  UKE                                       UK (England)
31  UKN                               UK(Northern Ireland)
32  UKS                                       UK(Scotland)
33   US                                      United States

In [5]:
f_cd_country_df.to_csv('cd_country_final.csv',index=False)